/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConfigurationsRouteImport } from './routes/configurations'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfigurationsIndexRouteImport } from './routes/configurations.index'

const ConfigurationsRoute = ConfigurationsRouteImport.update({
  id: '/configurations',
  path: '/configurations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigurationsIndexRoute = ConfigurationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConfigurationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configurations': typeof ConfigurationsRouteWithChildren
  '/configurations/': typeof ConfigurationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configurations': typeof ConfigurationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configurations': typeof ConfigurationsRouteWithChildren
  '/configurations/': typeof ConfigurationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/configurations' | '/configurations/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/configurations'
  id: '__root__' | '/' | '/configurations' | '/configurations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfigurationsRoute: typeof ConfigurationsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/configurations': {
      id: '/configurations'
      path: '/configurations'
      fullPath: '/configurations'
      preLoaderRoute: typeof ConfigurationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configurations/': {
      id: '/configurations/'
      path: '/'
      fullPath: '/configurations/'
      preLoaderRoute: typeof ConfigurationsIndexRouteImport
      parentRoute: typeof ConfigurationsRoute
    }
  }
}

interface ConfigurationsRouteChildren {
  ConfigurationsIndexRoute: typeof ConfigurationsIndexRoute
}

const ConfigurationsRouteChildren: ConfigurationsRouteChildren = {
  ConfigurationsIndexRoute: ConfigurationsIndexRoute,
}

const ConfigurationsRouteWithChildren = ConfigurationsRoute._addFileChildren(
  ConfigurationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfigurationsRoute: ConfigurationsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
